apiVersion: v1
kind: Service
metadata:
  labels:
    app: golang-docker-k8s
  name: golang-docker-k8s
spec:
  ports:
  - nodePort: 30080
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: golang-docker-k8s
  type: NodePort
